export const items = {
    "example.com": 2,
    "kaspahub.org": 1,
    "klearswap.com": 0,
    "dex.cc": -1,
    "kastra.org": -2,
    
    "kraken.com": 2,
    "uphold.com": 2,
    "topperpay.com": 1,
    "neverless.com": 1,
    "bybit.com": 1,
    "mexc.com": 1,
    "bingx.com": 1,
    "coinex.com": 1,
    "kucoin.com": 1,
    "poloniex.com": 1,
    "changelly.com": 1,
    "coinw.com": 1,
    "changenow.io": 1,
    
    "kaspa.org": 1,
    "kaspa.com": 1,
    "kasplex.org": 1,
    "kaspafoundation.org": 1,
    "kaspa-kii.org": 1,
    "kasway.xyz": 1,
    "kasmedia.com": 1,
    "kasia.fyi": 1,
    "kaspalife.org": 1,
    "kaspadaily.com": 1,
    "kaspafaq.com": 1,
    "kaspa-ai.com": 1,
    "kasphub.com": 1,
    "kas.fyi": 1,
    "kaspalytics.com": 1,
    "dagscan.xyz": 1,
    "katscan.xyz": 1,
    "kaspaglo.be": 1,
    "kaspa.ws": 1,
    "kasunder.com": 1,
    "kasnodes.com": 1,
    "kaspainsights.com": 1,
    "kasplore.com": 1,
    "kasware.xyz": 1,
    "kaspa-ng.org": 1,
    "kaspium.io": 1,
    "kastle.cc": 1,
    "kurncy.com": 1,
    "kaspanet.io": 1,




};
